// TASK MUTATIONS
export const CREATE_TASK = 'CREATE_TASK';
export const CLEAR_NEW_TASK = 'CLEAR_NEW_TASK';
export const UPDATE_NEW_TASK = 'UPDATE_NEW_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UNCOMPLETE_TASK = 'UNCOMPLETE_TASK';
export const CLEAR_COMPLETED_TASKS = 'CLEAR_COMPLETED_TASKS';
// ALERT MUTATIONS
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
